### ISSUE TITLE
Shapes asset

### ISSUE THREAD

**Issue by javl** [Redoxee/OutOfControlCardGame#1]
Hi,

This is a friendly reminder to let you know you (probably unintentionally) included the Shapes Unity asset to your repository. This asset is not open source and is not meant to shared publicly this way.

**Comment by Redoxee** [comment]
Whoops I'm terribly sorry, I've added it to my ignore list (and deleted it from the repo).
Is it fine or should I also rewrite the history (this seems hard though)?

**Comment by javl** [comment]
Anyone checking out an earlier version of the git repository will still have access to the files unfortunately. You should be able to completely remove the files from git, but I'm not 100% sure how but this help page by Github might help:
https://docs.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository

Thanks for your effort!

**Comment by Redoxee** [comment]
Git filter-branch did the trick like magic!
Asside from the folder meta I can't find shapes anymore in the history.
